// react_app/src/App.js
import logo from './logo.svg';
import './App.css';
import React, { useState } from "react";

function App() {
  const [email, setEmail] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [validEmail, setValidEmail] = useState(true);
  const [validFirstName, setValidFirstName] = useState(true);
  const [validLastName, setValidLastName] = useState(true);
  const [validPhone, setValidPhone] = useState(true);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!validateForm()) {
      return;
    }
    alert("Form Successfully Submitted!");
  };

  const validateForm = () => {
    let valid = true;
    if (!email.match(/^\S+@\S+\.\S+$/)) {
      setValidEmail(false);
      valid = false;
    } else {
      setValidEmail(true);
    }
    if (!firstName.match(/^[a-zA-Z\s]+$/)) {
      setValidFirstName(false);
      valid = false;
    } else {
      setValidFirstName(true);
    }
    if (!lastName.match(/^[a-zA-Z\s]+$/)) {
      setValidLastName(false);
      valid = false;
    } else {
      setValidLastName(true);
    }
    if (!phoneNumber.match(/^(09\d{2}-\d{3}-\d{4})$/)) {
      setValidPhone(false);
      valid = false;
    } else {
      setValidPhone(true);
    }
    return valid;
  };

  const inputClass = validEmail ? "" : "border-red-500";
  const inputFNameClass = validFirstName ? "" : "border-red-500";
  const inputLNameClass = validLastName ? "" : "border-red-500";
  const inputPhoneClass = validPhone ? "" : "border-red-500";
  const validForm = validEmail && validFirstName && validLastName && validPhone;


  return (
  <div className="flex justify-center items-center h-screen">
    <div className="rounded-lg bg-gray-100 p-8">
      <form className="w-full max-w-sm" onSubmit={handleSubmit}>

        <div className="md:flex md:items-center mb-6">
            <div className="md:w-1/3">
              <label
                className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                htmlFor="inline-full-name"
              >
                Email
              </label>
            </div>
            <div className="md:w-2/3">
              <input
                className={"appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline " + inputClass}
                id="inline-full-name"
                type="text"
                placeholder="JuanDeLaCruz@gmail.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              {!validEmail && (
                <span className="text-red-500 text-xs italic">
                  Please enter a valid email address.
                </span>
              )}
            </div>
        </div>

        <div className="md:flex md:items-center mb-6">
        <div className="md:w-1/3">
          <label
            className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
            htmlFor="inline-first-name"
          >
            First Name
          </label>
        </div>
        <div className="md:w-2/3">
          <input
            className={`${
              validFirstName ? "border-gray-300" : "border-red-500"
            } appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline`}
            id="inline-first-name"
            type="text"
            placeholder="Juan"
            value={firstName}
            onChange={(e) => {
              setFirstName(e.target.value);
              setValidFirstName(/^[A-Za-z\s]+$/.test(e.target.value));
            }}
          />
          {!validFirstName && (
            <span className="text-red-500 text-xs italic">
              Please enter a valid first name.
            </span>
          )}
        </div>
      </div>
      
      <div className="md:flex md:items-center mb-6">
        <div className="md:w-1/3">
          <label htmlFor="inline-last-name" className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4">
            Last Name
          </label>
        </div>
        <div className="md:w-2/3">
            <input 
              className={"appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline " + inputLNameClass}
              id="inline-last-name" 
              type="text" 
              placeholder="Dela Cruz" 
              value={lastName}
              onChange={(e) => setLastName(e.target.value)}
            />
            {!validLastName && <p className="text-red-500 text-xs italic">Please enter a valid last name.</p>}
          </div>
      </div>
      
      <div className="md:flex md:items-center mb-6">
        <div className="md:w-1/3">
          <label htmlFor="inline-phone-number" className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4">
            Phone Number
          </label>
        </div>
        <div className="md:w-2/3">
          <input 
            className={"appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline " + inputPhoneClass} 
            id="inline-phone-number" 
            type="text" 
            placeholder="09XX-XXX-XXXX" 
            value={phoneNumber}
            onChange={(e) => setPhoneNumber(e.target.value)}
          />
          {!validPhone && <p className="text-red-500 text-xs italic">Please enter a valid phone number.</p>}
        </div>
      </div>

      <div className="md:flex md:items-center">
        <div className="md:w-1/3"></div>
        <div className="md:w-2/3">
          <button 
            className="shadow bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" 
            type="submit" 
            disabled={!validForm} 
            onClick={(e) => handleSubmit(e)}
          >
            Submit
          </button>
        </div>
      </div>

      </form>
    </div>
  </div>
    
  );
}

export default App;

// Vue/vue-project/src/App.vue
<template>
  <div class="flex justify-center items-center h-screen">
    <div class="rounded-lg bg-gray-100 p-8">
      <form class="w-full max-w-sm">

      <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
          <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
            Email
          </label>
        </div>
        <div class="md:w-2/3">
          <input v-bind:class="inputClass" id="inline-full-name" type="text" placeholder="JuanDeLaCruz@gmail.com" v-model="email">          
          <span class="text-red-500 text-xs italic" v-if="!validEmail">Please enter a valid email address.</span>
        </div>
      </div>

      <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
          <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-first-name">
            First Name
          </label>
        </div>
        <div class="md:w-2/3">
          <input v-bind:class="inputFNameClass" id="inline-first-name" type="text" placeholder="Juan" v-model="firstName">
          <p class="text-red-500 text-xs italic" v-if="!validFirstName">Please enter a valid first name.</p>
        </div>
      </div>

      <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
          <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-last-name">
            Last Name
          </label>
        </div>
        <div class="md:w-2/3">
          <input v-bind:class="inputLNameClass" id="inline-last-name" type="text" placeholder="Dela Cruz" v-model="lastName">
          <p class="text-red-500 text-xs italic" v-if="!validLastName">Please enter a valid last name.</p>
        </div>
      </div>

      <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
          <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-phone-number">
            Phone Number
          </label>
        </div>
        <div class="md:w-2/3">
          <input v-bind:class="inputPhoneClass" id="inline-phone-number" type="text" placeholder="09XX-XXX-XXXX" v-model="phoneNumber">
          <p class="text-red-500 text-xs italic" v-if="!validPhone">Please enter a valid phone number.</p>
        </div>
      </div>

      <div class="md:flex md:items-center">
        <div class="md:w-1/3"></div>
        <div class="md:w-2/3">
          <button class="shadow bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="submit" :disabled="!validForm" @click="say('Form Successfully Submitted!')">
            Submit
          </button>
        </div>
      </div>

      </form>

    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      email: '',
      firstName: '',
      lastName: '',
      phoneNumber: ''
    }
  },
  computed: {
    validEmail() {
      const emailRegex = /^\S+@\S+\.\S+$/
      return emailRegex.test(this.email)
    },
    validFirstName() {
      const firstNameRegex = /^[a-zA-Z\s]+$/
      return firstNameRegex.test(this.firstName)
    },
    validLastName() {
      const lastNameRegex = /^[a-zA-Z\s]+$/
      return lastNameRegex.test(this.lastName)
    },
    validPhone() {
      const phoneRegex = /^(09\d{2}-\d{3}-\d{4})$/
      return phoneRegex.test(this.phoneNumber)
    },
    validForm() {
      return this.validEmail && this.validFirstName && this.validLastName && this.validPhone
    },

    inputClass() {
    if (!this.validEmail) {
      return "bg-gray-200 appearance-none border-2 border-red-500 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-500";
    } else {
      return "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500";
    }
    },
    inputFNameClass(){
    if (!this.validFirstName) {
      return "bg-gray-200 appearance-none border-2 border-red-500 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-500";
    }
    else {
      return "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500";
    }
    },
    inputLNameClass(){
    if (!this.validLastName) {
      return "bg-gray-200 appearance-none border-2 border-red-500 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-500";
    }
    else {
      return "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500";
    }
    },
    inputPhoneClass(){
    if (!this.validPhone) {
      return "bg-gray-200 appearance-none border-2 border-red-500 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-500";
    }
    else {
      return "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-green-500";
    }
    },
  },
  methods: {
    say(message){
      alert(message)
    }
  },
}
</script>

<style scoped>
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
</style>
